import { useQuery } from "@tanstack/react-query";
import { Link, useParams } from "react-router-dom";
import { api, type Decomposition, type Rule } from "../api";
import {
  ErrorNote, FACTOR_LABELS, Loading, Panel, ScoreCell, millis, whenAgo,
} from "../components";

function FactorWaterfall({ d }: { d: Decomposition["decomposition"] }) {
  const total = Math.max(
    1,
    d.factors.reduce((acc, f) => acc + f.contribution_millis, 0),
  );
  return (
    <div>
      {d.factors.map((f) => {
        const pct = Math.round((f.contribution_millis / total) * 100);
        return (
          <div className="factor-row" key={f.name}>
            <div>
              <div className="factor-name">{FACTOR_LABELS[f.name] ?? f.name}</div>
              <div className="factor-raw">{f.raw}</div>
            </div>
            <div className="factor-track">
              <div
                className="factor-bar"
                style={{ ["--pct" as string]: `${pct}%` }}
                title={`contribution ${millis(f.contribution_millis)} of ${millis(total)}`}
              />
              <div className="factor-weight-note">
                subscore {millis(f.subscore_millis)} × weight{" "}
                {millis(f.weight_millis)} → {pct}% of score
              </div>
            </div>
            <div className="factor-contrib">
              <b>{millis(f.contribution_millis)}</b>
              <span>contribution</span>
            </div>
          </div>
        );
      })}
    </div>
  );
}

export default function ThreatDetail() {
  const { cve } = useParams<{ cve: string }>();
  const decomp = useQuery({
    queryKey: ["decomposition", cve],
    queryFn: () =>
      api.get<Decomposition>(
        `/api/v1/priorities/${encodeURIComponent(cve!)}/decomposition`),
  });
  const rules = useQuery({
    queryKey: ["rules"],
    queryFn: () => api.get<{ rules: Rule[] }>("/api/v1/rules"),
  });

  if (decomp.isPending) return <Loading what={`decomposition for ${cve}`} />;
  if (decomp.isError) return <ErrorNote error={decomp.error} />;

  const d = decomp.data;
  const cveRules = (rules.data?.rules ?? []).filter((r) => r.cve === cve);

  return (
    <>
      <div className="page-head">
        <h1 className="mono">{cve}</h1>
        <span className="sub">
          scored by {d.scored_by} · weights{" "}
          <span className="mono">{d.decomposition.weights_version}</span> ·
          ledger seq <span className="mono">{d.ledger_seq}</span>
        </span>
      </div>

      <div className="detail-grid">
        <div>
          <Panel
            title="Score decomposition"
            aside={<ScoreCell millis={d.decomposition.priority_millis} />}
          >
            <FactorWaterfall d={d.decomposition} />
            <hr className="divider" />
            <p className="tiny faint" style={{ margin: 0 }}>
              This decomposition is served from the audit ledger entry that
              recorded the score — replaying that entry reproduces this
              number bit-for-bit.
            </p>
          </Panel>

          <Panel title={`Detection content (${cveRules.length})`}>
            {cveRules.length === 0 ? (
              <p className="muted" style={{ margin: 0 }}>
                No detection content compiled for this threat yet. Rules are
                generated by the detection factory from corroborated
                indicators and appear here for review.
              </p>
            ) : (
              <table className="grid">
                <thead>
                  <tr>
                    <th>Title</th><th>Format</th><th>Status</th>
                    <th className="num">FP est.</th><th>Created</th>
                  </tr>
                </thead>
                <tbody>
                  {cveRules.map((r) => (
                    <tr key={r.rule_id}>
                      <td>{r.title}</td>
                      <td className="mono">{r.format}</td>
                      <td><span className={`badge ${r.status}`}>{r.status}</span></td>
                      <td className="num mono">{millis(r.fp_estimate_millis)}%</td>
                      <td className="faint tiny">{whenAgo(r.created_at)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
            <p className="tiny" style={{ marginBottom: 0, marginTop: 10 }}>
              <Link to="/rules">Review and release rules →</Link>
            </p>
          </Panel>
        </div>

        <div>
          <Panel title="Audit trail">
            <table className="grid">
              <tbody>
                <tr>
                  <th style={{ borderTop: "none" }}>Ledger sequence</th>
                  <td className="mono">{d.ledger_seq}</td>
                </tr>
                <tr>
                  <th>Recorded at</th>
                  <td className="mono tiny">{d.scored_at}</td>
                </tr>
                <tr>
                  <th>Actor</th>
                  <td className="mono tiny">{d.scored_by}</td>
                </tr>
                <tr>
                  <th>Priority</th>
                  <td className="mono">{millis(d.decomposition.priority_millis)} / 100</td>
                </tr>
              </tbody>
            </table>
            <p className="tiny faint">
              The hash chain ties this entry to every prior decision on the
              tenant ledger; tampering breaks verification.
            </p>
          </Panel>
        </div>
      </div>
    </>
  );
}
