# Generated by Django 5.2.17 on 2026-09-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginFailure',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('ip_hash', models.CharField(default='', max_length=16)),
                ('failed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
